### ISSUE TITLE
Quick fix for electron compatiblity

### ISSUE THREAD

**Issue by BCNelson** [AlCalzone/shared-utils#328]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `alcalzone-shared@3.0.3` for the project I'm working on.

the wait utility does not work in the electron renderer process as setTimeout is a global function in the browser context but returns a number instead of an object.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/alcalzone-shared/async/index.js b/node_modules/alcalzone-shared/async/index.js
index e99256e..ce514cb 100644
--- a/node_modules/alcalzone-shared/async/index.js
+++ b/node_modules/alcalzone-shared/async/index.js
@@ -49,8 +49,9 @@ exports.promisifyNoError = promisifyNoError;
  */
 function wait(ms, unref = false) {
     return new Promise((resolve) => {
         const timeout = setTimeout(resolve, ms);
-        if (unref)
+        if (unref && typeof timeout != "number")
             timeout.unref();
     });
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AlCalzone** [comment]
Sounds good, but I would throw an error instead if `unref` is true and `setTimeout` returns a number. Otherwise you might think that the timeout was unref-ed when it actually wasn't.

Can you provide a PR for the change?

**Comment by BCNelson** [comment]
I would disagree that an error should be thrown as is it makes it a transparent change in browser there is no need to unref in a browser as your JavaScript can't stop the user form navigating away or closing the browser

**Comment by AlCalzone** [comment]
Fair enough

**Comment by AlCalzone** [comment]
v3.0.4 should fix this in a couple of minutes
